# Jekyll Resume Theme

# Site settings
title: ๏๏ɨ๏๏
email: info@ooioo.co
description: 
baseurl: "https://ooioo.co/"
url: "https://ooioo.co/"
name: KD
job: Front-End Engineer
location: IN
languages: HTML, CSS and Javascript
twitter_username: dkaarthik
github_username:  dkarthe
facebook_username: u4i.me 
email_address: info@ooioo.co



# Build settings
markdown: kramdown
