# Jekyll Resume Theme

# Site settings
title: ๏๏ɨ๏๏
email: info@ooioo.co
description: 
baseurl: "https://ooioo.co/"
url: "https://ooioo.co/"
name: ๏๏ɨ๏๏
job: Front-End Engineer
location: IN
languages: HTML, CSS and Javascript
twitter_username: dkaarthik
github_username:  dkarthe
email_address: info@ooioo.co
codepen_username:  


# Build settings
markdown: kramdown
