# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/ooioo/:title

# Setup
title:		ooioo
tagline:	''
description:	'My personal blog.'
url:		http://ooioo.co

author:
  name:		'KD'
  url:		https://twitter.com/dkaarthik

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/dkaarthik
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/dkarthe
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://google.com/
    desc:	Add me on google+karthikdkarthi

  - icon:	linkedin
    url:	http://facebook.com/kdcud
    desc:	Follow me on facebook
    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	KD
  url:		http://ooioo.co
  type_title:	Some rights reserved
  type_url:	http://ooioo.co
