# Site settings
title: Nice Blog
name: ๏๏ɨ๏๏ # your name
email: info@ooioo.co # your email address
description: >
    A Simple Blog By . # this means to ignore newlines until "baseurl:"
baseurl: "https://ooioo.co" # the subpath of your site, e.g. /blog
url: "https://ooioo.co" # the base hostname & protocol for your site
twitter_username: dkaarthik # your Twitter username
github_username: dkarthe # your Github username
disqus_username: ooioo # your disqus username

google-analytics: UA-98062322-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown

webmaster_verifications:
  google: lWaJLdxuNx0o2B4QgLD9Ou2IoF2yTFkGbNmrqgUK2Fo
  bing: 
  alexa: 
  yandex: 
