
title: My Resume
url: 'https://ooioo.co'
baseurl: 'https://ooioo.co' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Karthik D
tagline: Network Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: karthik.d@live.in
phone: +91-900-377-6115
website: ooioo.co #do not add http://
linkedin: dkaarthik
# github: dkarthe
twitter: '@dkaarthik'


# Tracker
#analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
